#!/bin/sh

rm -rf tmp
mkdir tmp
cd tmp

git init
git config user.email "alex@example.com"
git config user.name "Alex Ciminian"

cp ../fixtures/package.json .
cp ../fixtures/component.json .

git add .
git commit -m 'initial commit'

touch test.txt